name: Deploy

on:
  push:
    branches: main
  workflow_dispatch:

env:
  DOCKER_IMAGE: ''
  GCP_CLOUD_RUN_SERVICE_NAME: mcpbox-api



jobs:
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: |
          echo "DOCKER_IMAGE=${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}/${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GCP_GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.DOCKER_IMAGE }}" ./
          docker push "${{ env.DOCKER_IMAGE }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ vars.GCP_REGION }}
          image: ${{ env.DOCKER_IMAGE }}
          flags: |
            --port=8080
            --timeout=300
            --allow-unauthenticated
            --min-instances=1
          secrets: |
            KEYSTONE_GRAPHQL_SCHEMA_URL=KEYSTONE_GRAPHQL_SCHEMA_URL:latest
            CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest
            CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest
            CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest
            GCP_ADMIN_ACCOUNT_KEY=GCP_ADMIN_ACCOUNT_KEY:latest
            PUB_SUB_DEPLOYER_TOPIC=PUB_SUB_DEPLOYER_TOPIC:latest
          env_vars: |
            CORS_ORIGIN_WHITELIST=${{ vars.CORS_ORIGIN_WHITELIST }}
            

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      - name: Warm up service
        run: |
          for i in {1..5}; do
            curl -fsS "${{ steps.deploy.outputs.url }}" && exit 0
            echo "Retrying in 3s..."
            sleep 3
          done
          echo "Service did not respond successfully" && exit 1

      
